version: '3.8'

services: 
  node_backend:
    container_name: pomodorotimer
    image: pomodorotimer:0.0.1
    build: 
      context: ./server
    ports:
      - "3001:3001"
    environment: 
      - JWT_SECRET=AAAAAAAAAAAAAAaaaaaabbbbbCCCCCCffssssaaaqwdsadsdsdasdasdsdsd
      - EXTERNAL_PORT=3001
      - PGDATABASE=pomo_db
      - PGUSER=francesco
      - PGPASSWORD=12345
      - PGHOST=node_db
    depends_on: 
      - node_db
  node_db: 
    container_name: node_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=pomo_db
    volumes:
      - nps_data:/var/lib/postgresql/data
  
  # vue-frontend:
  #   container_name: vue_frontend
  #   build:
  #     context: ./client
  #   ports:
  #     - "8080:80"
volumes:
  nps_data: {}

  
    